#!/bin/bash
# vbox_create --- Create and configure a new VM
#
# Author: Haden Pike <haden.pike@gmail.com>
#
# Copyright (c) 2017 Haden Pike
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This script creates a virtual machine template for me to install an
# operating system into.
# Note that some OSs, notably Windows, install differently depending on
# some of these settings.
# See https://www.virtualbox.org/manual/ch08.html
# for a description of the VirtualBox CLI.

if [[ $# -lt 3 ]]; then
    echo "${0} VMName OSType install_iso"
    exit 1
fi

# Create the machine
VBoxManage createvm --name "${1}" --ostype "${2}" --basefolder "$(pwd -P)" --register
cd "${1}"

# Create the hard disk
VBoxManage createhd --filename "${1}.vdi" --size 20480

# Create and attach the storage to the VM
VBoxManage storagectl "${1}" --name "SATA" --add sata --hostiocache on --bootable on
VBoxManage storageattach "${1}" --storagectl "SATA" --port 0 --device 0 --type dvddrive --medium "${3}"
VBoxManage storageattach "${1}" --storagectl "SATA" --port 1 --device 0 --type hdd --medium "${1}.vdi"

# Change settings to my liking
VBoxManage modifyvm "${1}" --memory 1024 --acpi on --ioapic on --rtcuseutc on --pae on --hpet on --hwvirtex on --nestedpaging on --vtxvpid on --vtxux on --boot1 dvd --boot2 disk --nictype1 virtio --audio coreaudio --usb on
# Done!

